/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3.vista;

/**
 *
 * @author Jonathan Camacho
 */
public class VentanaLogIn extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogIn
     */
    public VentanaLogIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelIngreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelNombreUsuario1 = new javax.swing.JLabel();
        jFieldContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonConectarse = new javax.swing.JButton();
        jLabelNombreUsuario2 = new javax.swing.JLabel();
        jComboBoxIngreso = new javax.swing.JComboBox<>();
        jPanelRegistro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNombreUsuario3 = new javax.swing.JLabel();
        jLabelNombreUsuario4 = new javax.swing.JLabel();
        jTextRegistroApellido = new javax.swing.JTextField();
        jLabelNombreUsuario5 = new javax.swing.JLabel();
        jTextRegistroCorreo = new javax.swing.JTextField();
        jLabelNombreUsuario6 = new javax.swing.JLabel();
        jTextRegistroNombre = new javax.swing.JTextField();
        jLabelContraseña1 = new javax.swing.JLabel();
        jFieldConfirmarContraseña = new javax.swing.JPasswordField();
        jLabelContraseña2 = new javax.swing.JLabel();
        jFieldRegistroContraseña = new javax.swing.JPasswordField();
        jButtonRegistro = new javax.swing.JButton();
        jComboBoxRegisto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIngreso.setBackground(new java.awt.Color(33, 43, 65));
        jPanelIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_Shield_100px.png"))); // NOI18N
        jLabel3.setText("Ingreso de Usuario");
        jPanelIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Male_User_35px.png"))); // NOI18N
        jPanelIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(169, 224, 49));
        jLabelContraseña.setText("Contraseña:");
        jPanelIngreso.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jTextNombreUsuario.setBackground(new java.awt.Color(33, 43, 65));
        jTextNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jTextNombreUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextNombreUsuarioMouseMoved(evt);
            }
        });
        jTextNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreUsuarioActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jTextNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 310, 40));

        jLabelNombreUsuario1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario1.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario1.setText("Tipo de Usuario:");
        jPanelIngreso.add(jLabelNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jFieldContraseña.setBackground(new java.awt.Color(33, 43, 65));
        jFieldContraseña.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jFieldContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jFieldContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldContraseñaActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 310, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Lock_35px.png"))); // NOI18N
        jPanelIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(33, 43, 65));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(169, 224, 49));
        jButton1.setText("¿Olvido su contraseña?");
        jButton1.setBorder(null);
        jPanelIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jButtonConectarse.setBackground(new java.awt.Color(169, 224, 49));
        jButtonConectarse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonConectarse.setForeground(new java.awt.Color(33, 43, 65));
        jButtonConectarse.setText("Conectarse");
        jPanelIngreso.add(jButtonConectarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 260, 40));

        jLabelNombreUsuario2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario2.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario2.setText("Correo:");
        jPanelIngreso.add(jLabelNombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jComboBoxIngreso.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxIngreso.setForeground(new java.awt.Color(33, 43, 65));
        jComboBoxIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Administrador", "Cliente" }));
        jPanelIngreso.add(jComboBoxIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, -1));

        getContentPane().add(jPanelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 510));

        jPanelRegistro.setBackground(new java.awt.Color(33, 43, 65));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Male_User_100px.png"))); // NOI18N
        jLabel4.setText("Registro de Usuario:");
        jPanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabelNombreUsuario3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario3.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario3.setText("Apellido:");
        jPanelRegistro.add(jLabelNombreUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 20));

        jLabelNombreUsuario4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario4.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario4.setText("Tipo de Usuario:");
        jPanelRegistro.add(jLabelNombreUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextRegistroApellido.setBackground(new java.awt.Color(33, 43, 65));
        jTextRegistroApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextRegistroApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTextRegistroApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jTextRegistroApellido.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextRegistroApellidoMouseMoved(evt);
            }
        });
        jTextRegistroApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRegistroApellidoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jTextRegistroApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 160, 40));

        jLabelNombreUsuario5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario5.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario5.setText("Correo:");
        jPanelRegistro.add(jLabelNombreUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jTextRegistroCorreo.setBackground(new java.awt.Color(33, 43, 65));
        jTextRegistroCorreo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextRegistroCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jTextRegistroCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jTextRegistroCorreo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextRegistroCorreoMouseMoved(evt);
            }
        });
        jTextRegistroCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRegistroCorreoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jTextRegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 330, 40));

        jLabelNombreUsuario6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelNombreUsuario6.setForeground(new java.awt.Color(169, 224, 49));
        jLabelNombreUsuario6.setText("Nombre:");
        jPanelRegistro.add(jLabelNombreUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jTextRegistroNombre.setBackground(new java.awt.Color(33, 43, 65));
        jTextRegistroNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextRegistroNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextRegistroNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jTextRegistroNombre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextRegistroNombreMouseMoved(evt);
            }
        });
        jTextRegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRegistroNombreActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jTextRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, 40));

        jLabelContraseña1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelContraseña1.setForeground(new java.awt.Color(169, 224, 49));
        jLabelContraseña1.setText("Confirmar contraseña:");
        jPanelRegistro.add(jLabelContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jFieldConfirmarContraseña.setBackground(new java.awt.Color(33, 43, 65));
        jFieldConfirmarContraseña.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jFieldConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jFieldConfirmarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jFieldConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldConfirmarContraseñaActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jFieldConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 310, 40));

        jLabelContraseña2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelContraseña2.setForeground(new java.awt.Color(169, 224, 49));
        jLabelContraseña2.setText("Contraseña:");
        jPanelRegistro.add(jLabelContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jFieldRegistroContraseña.setBackground(new java.awt.Color(33, 43, 65));
        jFieldRegistroContraseña.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jFieldRegistroContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jFieldRegistroContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jFieldRegistroContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldRegistroContraseñaActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jFieldRegistroContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 310, 40));

        jButtonRegistro.setBackground(new java.awt.Color(169, 224, 49));
        jButtonRegistro.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonRegistro.setForeground(new java.awt.Color(33, 43, 65));
        jButtonRegistro.setText("Registrarse");
        jPanelRegistro.add(jButtonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 260, 40));

        jComboBoxRegisto.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxRegisto.setForeground(new java.awt.Color(33, 43, 65));
        jComboBoxRegisto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Administrador", "Cliente" }));
        jPanelRegistro.add(jComboBoxRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, -1));

        getContentPane().add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 460, 510));

        jPanel3.setBackground(new java.awt.Color(33, 43, 65));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                 para tener acceso a la Tienda");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido a Peluchin, por favor ingrese los datos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel5)
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(197, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(161, 161, 161)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel6)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioMouseMoved

    }//GEN-LAST:event_jTextNombreUsuarioMouseMoved

    private void jTextNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreUsuarioActionPerformed

    private void jFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldContraseñaActionPerformed

    private void jTextRegistroApellidoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextRegistroApellidoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroApellidoMouseMoved

    private void jTextRegistroApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRegistroApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroApellidoActionPerformed

    private void jTextRegistroCorreoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextRegistroCorreoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroCorreoMouseMoved

    private void jTextRegistroCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRegistroCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroCorreoActionPerformed

    private void jTextRegistroNombreMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextRegistroNombreMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroNombreMouseMoved

    private void jTextRegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRegistroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegistroNombreActionPerformed

    private void jFieldConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldConfirmarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldConfirmarContraseñaActionPerformed

    private void jFieldRegistroContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldRegistroContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldRegistroContraseñaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonConectarse;
    public javax.swing.JButton jButtonRegistro;
    public javax.swing.JComboBox<String> jComboBoxIngreso;
    public javax.swing.JComboBox<String> jComboBoxRegisto;
    public javax.swing.JPasswordField jFieldConfirmarContraseña;
    public javax.swing.JPasswordField jFieldContraseña;
    public javax.swing.JPasswordField jFieldRegistroContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelContraseña2;
    private javax.swing.JLabel jLabelNombreUsuario1;
    private javax.swing.JLabel jLabelNombreUsuario2;
    private javax.swing.JLabel jLabelNombreUsuario3;
    private javax.swing.JLabel jLabelNombreUsuario4;
    private javax.swing.JLabel jLabelNombreUsuario5;
    private javax.swing.JLabel jLabelNombreUsuario6;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanelIngreso;
    public javax.swing.JPanel jPanelRegistro;
    public javax.swing.JTextField jTextNombreUsuario;
    public javax.swing.JTextField jTextRegistroApellido;
    public javax.swing.JTextField jTextRegistroCorreo;
    public javax.swing.JTextField jTextRegistroNombre;
    // End of variables declaration//GEN-END:variables
}
